app:
  title: "集成助手"
  theme: "default"
  debug: false

server:
  use_langraph: true  # 是否使用Langraph架构
  host: "127.0.0.1"
  port: 8000

llm:
  model: "local"  # local, openai, etc.
  model_path: "./models/llm"
  embedding_model: "local"
  embedding_model_path: "./models/embedding"
  # AnythingLLM集成配置
  anything_llm:
    enabled: true
    api_url: "http://localhost:3001"
    api_key: "A3QKACB-NVW40SY-HZJ8BE9-5960K5B"  # 如需设置API密钥，请在此处填写

meeting:
  audio_dir: "./data/audio"
  transcription_dir: "./data/transcriptions"
  whisper:
    model: "base"  # tiny, base, small, medium, large
    language: "auto"  # 默认语言，可选auto
    use_onnx: true  # 是否使用 ONNX 运行时版本的 Whisper

email:
  sync_interval: 300  # 秒
  max_emails: 1000
  providers:
    - name: "gmail"
      enabled: false
      credentials_file: "./credentials/gmail.json"

knowledge:
  docs_dir: "./data/documents"
  chunk_size: 1000
  chunk_overlap: 200
  embedding_model: "all-MiniLM-L6-v2"  # sentence-transformers模型名称
  splitter_type: "smart"  # 分块器类型：simple, markdown, smart
  supported_extensions:  # 支持的文件扩展名
    - ".txt"
    - ".md"
    - ".pdf"
    - ".docx"
    - ".html"
    - ".csv"
  use_mock_embedder: false  # 是否使用模拟嵌入器（用于测试）
  vector_search_top_k: 5  # 向量搜索返回的最大结果数

db:
  sqlite_path: "./data/app.db"
  vector_db_path: "./data/vector_db"

mcp:
  server_host: "127.0.0.1"
  server_port: 5000
  max_workers: 4
